Repository UB-CSE/course-project-a4-group, pull requests merged in 2020-10, with the labels that each got.

#53 Shop buttons
  GoodGames/GoodGames/urls.py
  GoodGames/game/.DS_Store
  GoodGames/game/static/.DS_Store
  GoodGames/game/static/shop/.DS_Store
  GoodGames/game/static/shop/css/buttons.css
  GoodGames/game/static/shop/css/style.css
  GoodGames/game/templates/game/shop.html
  GoodGames/users/forms.py
  GoodGames/users/migrations/0001_initial.py
  GoodGames/users/models.py
  GoodGames/users/templates/users/buy.html
  GoodGames/users/views.py
Labels: Sprint 2, Task

#54 Deploy
  GoodGames/GoodGames/settings.py
  GoodGames/Procfile
  GoodGames/requirements.txt
Labels: Sprint 2, Task

#57 #40 profile page
  GoodGames/game/templates/game/profile.html
  GoodGames/game/urls.py
  GoodGames/game/views.py
Labels: Sprint 2

#61 creation of the statistics page #60
  GoodGames/GoodGames/settings.py
  GoodGames/game/static/.DS_Store
  GoodGames/game/static/stats/.DS_Store
  GoodGames/game/static/stats/css/stats.css
  GoodGames/game/static/stats/js/stats-index.js
  GoodGames/game/templates/game/base.html
  GoodGames/game/templates/game/stats.html
  GoodGames/game/urls.py
  GoodGames/game/views.py
Labels: Sprint 2

#62 Edit profile
  GoodGames/game/templates/game/base.html
  GoodGames/game/templates/game/home.html
  GoodGames/game/templates/game/profile.html
  GoodGames/game/views.py
  GoodGames/users/templates/users/login.html
  GoodGames/users/templates/users/register.html
Labels: Sprint 2

#66 Database
  GoodGames/gameMatchResult/admin.py
  GoodGames/gameMatchResult/migrations/0001_initial.py
  GoodGames/gameMatchResult/models.py
  GoodGames/users/migrations/0008_auto_20201018_2320.py
  GoodGames/users/models.py
Labels: Sprint 3
